### ISSUE TITLE
오라클 프리티어에 설치했는데 tsharp 이 자꾸 죽네요.

### ISSUE THREAD

**Issue by htogether** [banyazavi/tsharp#4]
이유를 모르겠습니다. 인스탄스 재시작도 해보고 컨테이너 재시작, 다시 생성을 해도 접속자체가 안됩니다.
   __                                      ___ 

  / /_____  _______________________  ____ |__ \

 / __/ __ \/ ___/ ___/ ___/ ___/ _ \/ __ \__/ /

/ /_/ /_/ / /  / /  (__  |__  )  __/ / / / __/ 

\__/\____/_/  /_/  /____/____/\___/_/ /_/____/ 

 :: Spring Boot ::           (v2.3.3.RELEASE)                                       

2022-04-09 02:36:05,031 INFO  [main] org.springframework.boot.StartupInfoLogger: Starting Torrssen2Application on d9ce8038a7a1 with PID 50 (/torrssen2.jar started by root in /)

2022-04-09 02:36:05,106 INFO  [main] org.springframework.boot.SpringApplication: The following profiles are active: default

2022-04-09 02:37:13,605 INFO  [main] org.springframework.boot.StartupInfoLogger: Started Torrssen2Application in 74.691 seconds (JVM running for 79.821)

2022-04-09 02:38:03,336 ERROR [XNIO-1 task-1] org.springframework.web.socket.server.support.AbstractHandshakeHandler: Handshake failed due to invalid Upgrade header: null

2022-04-09 02:40:17,838 ERROR [XNIO-1 task-2] com.tarpha.torrssen2.service.TransmissionService: Connect to tm.joajoa.duckdns.org:9091 [tm.joajoa.duckdns.org/125.239.195.188] failed: Connection timed out (Connection timed out)

2022-04-09 02:40:17,844 ERROR [scheduled-task-pool-1] org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler: Unexpected error occurred in scheduled task

java.lang.IllegalStateException: Connection pool shut down

	at org.apache.http.util.Asserts.check(Asserts.java:34)

	at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:196)

	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:268)

	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)

	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)

	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)

	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

	at com.tarpha.torrssen2.service.TransmissionService.execute(TransmissionService.java:174)

	at com.tarpha.torrssen2.service.TransmissionService.torrentGet(TransmissionService.java:271)

	at com.tarpha.torrssen2.service.SchedulerService.transmissionJob(SchedulerService.java:115)

	at com.tarpha.torrssen2.service.SchedulerService.runTask(SchedulerService.java:54)

	at com.tarpha.torrssen2.config.SchedulerConfig.lambda$configureTasks$2(SchedulerConfig.java:51)

	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)

	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

**Comment by htogether** [comment]
결국 포기하고 모든 디렉토리 지우고 재설치했습니다. 일단은 다시 실행되는 상태입니다.
